{% set name = "glue-jupyter" %}
{% set version = "0.22.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 49a05c820b91918547038def2237212a6701c3e57071d6240c81dddaf7a2c09e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - glue-core >=1.7.0
    - glue-vispy-viewers >=1.0
    - notebook >=4.0
    - ipympl >=0.3.0
    - ipyvolume >=0.5.0
    - ipywidgets >=7.4.0
    - ipyvue >=1.2.0,<2
    - ipyvuetify >=1.2.0,<2
    - bqplot-image-gl >=1.4.3
    - bqplot >=0.12.17
    - scikit-image

test:
  imports:
    - glue_jupyter
    - glue_jupyter.app
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/glue-viz/glue-jupyter
  summary: Glue front-end for the Jupyter ecosystem
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://glue-jupyter.readthedocs.io/en/latest/
  dev_url: https://github.com/glue-viz/glue-jupyter

extra:
  recipe-maintainers:
    - astrofrog
    - maartenbreddels
    - trungleduc
    - martinRenou
