{% set name = "glue-jupyter" %}
{% set version = "0.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ddf6388ab4de15b1ec833d1361d9fd9c30628e5fde93519e2706004a7cc75c81

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - glue-core >=1.7.0
    - glue-vispy-viewers >=1.0
    - notebook >=4.0
    - ipympl >=0.3.0
    - ipyvolume >=0.5.0
    - ipywidgets >=7.4.0
    - ipyvue >=1.2.0,<2
    - ipyvuetify >=1.2.0,<2
    - bqplot-image-gl >=1.4.3
    - bqplot >=0.12.17
    - scikit-image

test:
  imports:
    - glue_jupyter
    - glue_jupyter.app
  requires:
    - pip

about:
  home: https://github.com/glue-viz/glue-jupyter
  summary: Glue front-end for the Jupyter ecosystem
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://glue-jupyter.readthedocs.io/en/latest/
  dev_url: https://github.com/glue-viz/glue-jupyter

extra:
  recipe-maintainers:
    - astrofrog
    - maartenbreddels
    - trungleduc
    - martinRenou
